### ISSUE TITLE
list_http function only works for certain urls

### ISSUE THREAD

**Issue by lancewatkins** [nasa/dnppy#28]
Line 14: files.append(line.replace('/',' ').split(' " ')[5]) is only set to work with directory or file path that is structured the same as the example provided, http://e4ftl01.cr.usgs.gov/

I am attempting to use the function on http://water.weather.gov/precip/p_download_new/ 
And I'm not getting the right string names as a result. I think this issue has to do with the 5 in Line 14.

**Comment by Jwely** [comment]
the approach has been changed for fetching from websites using http. Separate http filelisting functions have been developed for the two current http download servers being used. Adding new http fetch support for new servers will require the creation of new list_http functions. These usually dont take long to create anyways.
list_http_e4ftl01
list_http_waterweather
