### ISSUE TITLE
extract_NetCDF not reading outdir

### ISSUE THREAD

**Issue by lancewatkins** [nasa/dnppy#36]
the extract_NetCDF tool in the precipitation module is not reading the appropriate output directory when the Copy Raster function is used to save the resulting tif file. It keeps saving the files in the same folder the original nc files are in.

**Comment by Jwely** [comment]
If you are talking about the  "extract_TRMM_NetCDF" function the issue has been resolved, on the next major update, this function will be moved to the "convert" module.
