### ISSUE TITLE
Many-Stats NoData Issue

### ISSUE THREAD

**Issue by jayz0113** [nasa/dnppy#43]
When averaging rasters with enf_rastlist and many_stats, the many_stats function changes NoData values within extent to 0 values when it should stay as NoData values.  Therefore, when I have the final averaged raster, there are a lot of 0 values that show up where it should really be NoData.  This is throwing off the raster properties.  Is there a way to keep  NoData values as NoData?

**Comment by Jwely** [comment]
Thanks for submitting this issue, I've made a commit that allows the user to input a key word argument for NoData values that defaults to -9999. Redownload and install the master branch and see if this resolves your issue.

**Comment by Jwely** [comment]
Just tried to replicate this issue and couldn't duplicate the behavior. Haven't heard anything new in over a month, so I'm closing this issue.
