### ISSUE TITLE
pip_install.py gets truncated on dowload

### ISSUE THREAD

**Issue by Jwely** [nasa/dnppy#49]
laptop on wifi seems to truncate the pip install script on download. not sure why yet.

**Comment by Syntaf** [comment]
I'm running WIFI on my desktop at home and the pip_install.py seems to have downloaded correctly, am I looking at the wrong piece of code?

```
def get_pip():
    """ ensures pip is installed"""

    try:
        import pip

    except ImportError:
        with open("install_pip.py", 'wb+') as f:
            connection = urllib.urlopen("https://bootstrap.pypa.io/get-pip.py")
            page = connection.read()
            f.write(page)
            f.close()
            del connection

        # run pip and clean up.
        import install_pip
        os.system("install_pip.py")
        os.remove("install_pip.py")
    return
```

**Comment by Jwely** [comment]
this is the right piece of code. Only on doctor Ross's laptop in the conference room did this occur. It didn't download that entire string of text characters that contains the pip binary information. That means it missed the tripple double quotes at the end and fails due to syntax on `import install_pip`.

I really can't figure out why that happened, but it happened twice, and cut off the script at different points each time. It is possible the wifi and the laptop have nothing to do with the problem. Hard drive space was plentiful enough to be an unlikely cause.

**Comment by Jwely** [comment]
After repeated attempt, we haven't been able to reproduce this result anywhere.
