### ISSUE TITLE
sphinx automodule uses excessively long function names

### ISSUE THREAD

**Issue by Jwely** [nasa/dnppy#52]
The documentation pages are incomplete,  but the core module is online as a starting test case. (https://nasa-develop.github.io/dnppy/modules/core.html#code-help)

Full paths to function names are used by sphinx's automodule call, and while tediously accurate, it isn't very readable. It would be nice to take just the last element, the function name.

**Comment by Syntaf** [comment]
Try changing `add_module_names´ to False in _conf.py_ , I'll test this later since I'm currently on mobile

**Comment by Jwely** [comment]
That is exactly what i was looking for. solved.
