### ISSUE TITLE
easy install did not install all dependencies 

### ISSUE THREAD

**Issue by lancewatkins** [nasa/dnppy#73]
I'm trying to install dnppy onto a laptop with Arc10.2. I downloaded the zip file, unzipped everything, then ran easy_install. Several of the libraries came back with  the error: BadZipfile: File is not a zip file and did not install. 

Libraries that failed: cython, pycurl, scipy, h5py, numpy, gdal, shapely

**Comment by Jwely** [comment]
Fixed an issue that used to cause this bug with commit a436aba2ce9f793da2980e8ab05f88c7f669756f.

This issue was definitely fixed one before. Not sure how it got reintroduced. Redownload the master branch and try again, let me know if problems persist.

**Comment by lancewatkins** [comment]
okay I'll redownload and try again
