### ISSUE TITLE
Issue with installation of dnppy

### ISSUE THREAD

**Issue by lancewatkins** [nasa/dnppy#74]
I'm attempting to help a friend install dnppy and we came across this issue. All the dependencies appear to have been installed 

![image](https://cloud.githubusercontent.com/assets/10967350/9771346/4927b93a-56ea-11e5-8c8a-9d98536d5520.png)

**Comment by Jwely** [comment]
Made a commit that might fix the issue. Please give the newest version of the master branch a try.

**Comment by Jwely** [comment]
looks like this issue is now resolved.
