### ISSUE TITLE
Getting an error message when running toa reflectance corrections 

### ISSUE THREAD

**Issue by bmrober4** [nasa/dnppy#75]
We are running the script for toa_reflectance and keep getting an error that it can not find the grab_meta module. I have not changed anything in the script except to add the file path and the band numbers and I am storing it all in the same folder. I have downloaded the dnnpy package and can find the module in the folder but the script cannot seem to find it.

**Comment by Jwely** [comment]
Thanks for reporting this issue, an attempted fix has been made. Download and install dnppy again. If an error persists, please come back and copy/paste the precise error.

**Comment by bmrober4** [comment]
Hi Jeff, thanks for looking at it. I am still getting the same error (with the object names changed):
Traceback (most recent call last):
  File "<pyshell#0>", line 3, in <module>
    from landsat_metadata import landsat_metadata
ImportError: No module named landsat_metadata

We have reviewed the directories and file locations and it seems like it is setup correctly... Not sure what the issue could be.

**Comment by Syntaf** [comment]
@bmrober4 how are you calling the script? Are you using an IDE or calling it from the command line?

EDIT: You may want to post just your source code related to this problem as well, that way jeff or I could test it ourselves

**Comment by bmrober4** [comment]
@Syntaf we have tried running it from the command line, through an IDE (Liclipse) and from a Python Shell. I have not changed any code except to add the metadata file path to the code from the toa_reflectance.py file in the dnnpy download.

**Comment by stapleCamel** [comment]
Searching on stackoverflow suggests its a problem with [the module's __init__.py](http://stackoverflow.com/questions/338768/python-importerror-no-module-named). I don't see anything immediately wrong with landsat/__init__.py, but there may be a [hidden Windows character](http://stackoverflow.com/a/339333) that messing it up.

**Comment by Syntaf** [comment]
@bmrober4 Has your issue been resolved?

**Comment by bmrober4** [comment]
Hi Grant,

The issue was not completely resolved but we ended up moving in a different direction to resolve our issue.

Thanks
