### ISSUE TITLE
'str' object is not callable during easy_install.py

### ISSUE THREAD

**Issue by Syntaf** [nasa/dnppy#76]
I tried installing dnppy on my linux machine today, but I came across an error when attempting to build dnppy. Here are the steps to reproduce
- Grab a fresh zip from master
- extract and run `sudo python easy_install.py`

Error.dat:

```
sh: 1: install_pip.py: not found
Downloading/unpacking pip from https://pypi.python.org/packages/py2.py3/p/pip/pip-7.1.2-py2.py3-none-any.whl#md5=5ff9fec0be479e4e36df467556deed4d
Installing collected packages: pip
  Found existing installation: pip 1.5.4
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed pip
Cleaning up...
Not uninstalling numpy at /usr/lib/python2.7/dist-packages, owned by OS
Not uninstalling numpy at /usr/lib/python2.7/dist-packages, owned by OS
Requirement already satisfied (use --upgrade to upgrade): mock in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): mock in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): mock in /usr/local/lib/python2.7/dist-packages
Cleaning up...
Cleaning up...
Cleaning up...
Traceback (most recent call last):
  File "easy_install.py", line 9, in <module>
    install_dependencies.main()
  File "/home/gdev/Downloads/dnppy-master/install_dependencies.py", line 237, in main
    check_process_lock()
  File "/home/gdev/Downloads/dnppy-master/install_dependencies.py", line 96, in check_process_lock
    name = proc.name()
TypeError: 'str' object is not callable
```

**Comment by Syntaf** [comment]
Didn't correctly read the webpage requirement

`Windows OS`

bummer I can't help test dnppy as the repository relies on proprietary software :/ . Was hoping to help solve the recent issue

**Comment by Jwely** [comment]
I've been doing extensive work with gdal lately and bult up a library of functions similar to some of those in dnppy but without the arcpy dependency. When i get the time i will start replacing some of the dnppy functions.

The raster module and the landsat module are the big culprits for arcpy dependence, with just a few key functions really being the choke points such as `raster.to_numpy()` and `raster.from_numpy()`
