### ISSUE TITLE
Wrong SAVI formula in surface_temp.py

### ISSUE THREAD

**Issue by PatrickImbo** [nasa/dnppy#83]
in  dnppy/dnppy/landsat/surface_temp.py

savi = ((1 + L) \* (nir - red))/(L + (nir + red))

instead of :

savi = ((1 + L) \* (nir - red))/(L + (nir - red))

Regards,
Patrick

**Comment by stapleCamel** [comment]
Thanks for the heads up.
Fixed with 291395eee4e270bc52f05adca1a31a432721a3aa
